#!/usr/bin/env python3
"""Inject per-page canonical and OpenGraph tags into every docs page.

The Lotus theme emits a title, a meta description and JSON-LD, but no
<link rel="canonical"> and no og:/twitter: tags, and it has no per-page hook for
them beyond frontmatter. Rather than hand-maintain that block in 25 files, this
script derives it from each page's own title, description and route.

The site origin is read from astro.config.ts, so there is exactly one place to
change when the custom domain lands.

Idempotent: re-running replaces the generated block rather than stacking copies.
Run it after adding a page or changing a title/description:

    python3 scripts/sync-page-meta.py
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "src" / "content" / "docs"
BEGIN = "  # >>> generated by scripts/sync-page-meta.py — do not edit by hand"
END = "  # <<< end generated"


def site_origin() -> str:
    config = (ROOT / "astro.config.ts").read_text(encoding="utf-8")
    match = re.search(r"site:\s*['\"]([^'\"]+)['\"]", config)
    if not match:
        sys.exit("astro.config.ts has no `site:` — cannot build canonical URLs.")
    return match.group(1).rstrip("/")


def route_for(path: pathlib.Path) -> str:
    rel = path.relative_to(DOCS).with_suffix("")
    parts = [p for p in rel.parts if p != "index"]
    return "/" + "".join(f"{p}/" for p in parts)


def scalar(frontmatter: str, key: str) -> str | None:
    """Read a top-level single-line scalar. Enough for `title` and `description`."""
    match = re.search(rf"^{key}:[ \t]*(.+?)[ \t]*$", frontmatter, re.MULTILINE)
    if not match:
        return None
    value = match.group(1)
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        value = value[1:-1]
    return value


# The theme renders <title> as "{page title} - {site name}", which on the homepage
# would read "Research Scan - Research Scan". A title tag in the page head wins.
HOME_TITLE = "Research Scan — evidence pipeline for reasoning agents"


def block(url: str, title: str, description: str | None, origin_url: str, is_home: bool) -> str:
    tags: list[tuple[str, dict[str, str]]] = []
    if is_home:
        tags.append(("title", {}))
    tags += [
        ("link", {"rel": "canonical", "href": url}),
        ("meta", {"property": "og:url", "content": url}),
        ("meta", {"property": "og:title", "content": title}),
    ]
    if description:
        tags.append(("meta", {"property": "og:description", "content": description}))
        tags.append(("meta", {"name": "twitter:description", "content": description}))
    tags.append(("meta", {"name": "twitter:title", "content": title}))
    # Absolute, because OpenGraph consumers do not resolve relative image URLs.
    tags.append(("meta", {"property": "og:image", "content": f"{origin_url}/og.png"}))
    tags.append(("meta", {"name": "twitter:image", "content": f"{origin_url}/og.png"}))

    lines = [BEGIN, "head:"]
    for tag, attrs in tags:
        lines.append(f"  - tag: {tag}")
        if tag == "title":
            lines.append(f"    content: {json.dumps(HOME_TITLE, ensure_ascii=False)}")
            continue
        lines.append("    attrs:")
        for name, value in attrs.items():
            lines.append(f"      {name}: {json.dumps(value, ensure_ascii=False)}")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    origin = site_origin()
    pages = sorted(DOCS.rglob("*.mdx"))
    if not pages:
        sys.exit(f"no .mdx pages under {DOCS}")

    changed = 0
    for page in pages:
        text = page.read_text(encoding="utf-8")
        match = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
        if not match:
            print(f"  skip (no frontmatter): {page.relative_to(ROOT)}")
            continue

        frontmatter = match.group(1)
        # Drop any previously generated block before reading the page's own keys.
        frontmatter = re.sub(
            rf"\n?{re.escape(BEGIN)}\n.*?{re.escape(END)}", "", frontmatter, flags=re.DOTALL
        )

        title = scalar(frontmatter, "title")
        if not title:
            print(f"  skip (no title): {page.relative_to(ROOT)}")
            continue
        description = scalar(frontmatter, "description")
        url = origin + route_for(page)

        rebuilt = f"---\n{frontmatter}\n{block(url, title, description, origin, route_for(page) == "/")}\n---\n"
        updated = rebuilt + text[match.end() :]
        if updated != page.read_text(encoding="utf-8"):
            page.write_text(updated, encoding="utf-8")
            changed += 1
        print(f"  {url}")

    print(f"\n{len(pages)} pages, {changed} updated. Origin: {origin}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
